#!/bin/bash

dirs=`find . -mindepth 1 -maxdepth 1 -type d`

printf "# autogenerated by cmd/build_registerPlugins\n\n"
printf "package cmd\n\nimport (\n"

plugins=""
for dir in $dirs
do
	file=$dir/$dir.go
	if [ -r $file ]
	then
		awk -v RS='^$' 'END{exit !(index($0,"Init") && index($0,"PreRun") && index($0,"PostRun") && index($0,"Name") && index($0,"Version") && index($0,"Description") && index($0,"Register"))}' $file
		if [ $? -eq 0 ]
		then
			plugins="$plugins `basename $dir`"
		fi	
	fi
done

for plugin in $plugins
do
	printf "\t\"github.com/dacb/goabe/%s\"\n" $plugin
done

printf ")\n\nfunc registerPlugins() {\n"

for plugin in $plugins
do
	printf "\t%s.Register()\n" $plugin
done


printf "}\n"
